MaisSaude/Controllers/Area/Operador/ClinicaController.cs
using MaisSaude.Extensoes;
using MaisSaude.Models;
using MaisSaude.Models.tUser;
using MaisSaude.Models.tUser.tClinica;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace MaisSaude.Controllers.Area.Operador
{
    //[Authorize(Roles = "4")]//clinica
    public class ClinicaController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IOptions<DadosBase> _DadosBase;
        private readonly IApiToken _IApiToken;

        public ClinicaController(IHttpClientFactory Client, IHttpContextAccessor cookies, IOptions<DadosBase> dadosBase, IApiToken iApiToken)
        {
            _httpClient = Client.CreateClient();
            _httpClient.DefaultRequestHeaders.Accept.Clear();
            _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            _DadosBase = dadosBase;
            _IApiToken = iApiToken;
        }
        public async Task<ActionResult> Index(string mensagem = null, bool sucesso = true)
        {
            try
            {
                if (sucesso)
                    TempData["sucesso"] = mensagem;
                else
                    TempData["erro"] = mensagem;

                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await _IApiToken.Obter());
                HttpResponseMessage response = await _httpClient.GetAsync($"{_DadosBase.Value.API_URL_BASE}Clinica/GetClinicas");

                if (response.IsSuccessStatusCode)
                    return View(JsonConvert.DeserializeObject<List<tUser>>(await response.Content.ReadAsStringAsync()));
                else
                    return View();
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult Create()
        {
            tClinicaRetorno tClinicaRetorno = new tClinicaRetorno
            {
                tUser = new tUser
                {
                    Ativo = true,
                    DataCriacao = DateTime.Now,
                }
            };

            return View(tClinicaRetorno);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(tClinicaRetorno tClinicaRetorno)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await _IApiToken.Obter());
                    HttpResponseMessage response = await _httpClient.PostAsJsonAsync($"{_DadosBase.Value.API_URL_BASE}Clinica/CreateClinica", tClinicaRetorno);

                    if (response.IsSuccessStatusCode)
                        return RedirectToAction(nameof(Index), new { mensagem = "Salvo com sucesso", sucesso = true });
                    else
                        return View(tClinicaRetorno);
                }
                else
                {
                    return View(tClinicaRetorno);
                }
            }
            catch
            {
                return View();
            }
        }


        public async Task<ActionResult> Edit(int ID)
        {
            try
            {
                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await _IApiToken.Obter());
                HttpResponseMessage response = await _httpClient.GetAsync($"{_DadosBase.Value.API_URL_BASE}Titular/GetTitular?ID={ID}");

                if (response.IsSuccessStatusCode)
                    return View(JsonConvert.DeserializeObject<tClinicaRetorno>(await response.Content.ReadAsStringAsync()));
                else
                    return View();
            }
            catch (Exception)
            {
                throw;
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(tClinicaRetorno tClinicaRetorno)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await _IApiToken.Obter());
                    HttpResponseMessage response = await _httpClient.PutAsJsonAsync($"{_DadosBase.Value.API_URL_BASE}Clinica/UpdateClinica", tClinicaRetorno);

                    if (response.IsSuccessStatusCode)
                        return RedirectToAction(nameof(Index), new { mensagem = "Editado com sucesso", sucesso = true });
                    else
                        return View(tClinicaRetorno);
                }
                else
                {
                    return View(tClinicaRetorno);
                }
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(int id)
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MaisSaude/Controllers/Area/Operador/MedicoController.cs
using MaisSaude.Extensoes;
using MaisSaude.Models;
using MaisSaude.Models.tUser;
using MaisSaude.Models.tUser.tMedico;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace MaisSaude.Controllers.Area.Operador
{
    //[Authorize(Roles = "4")]//clinica
    public class MedicoController : Controller
    {


        private readonly HttpClient _httpClient;
        private readonly IOptions<DadosBase> _DadosBase;
        private readonly IApiToken _IApiToken;

        public MedicoController(IHttpClientFactory Client, IHttpContextAccessor cookies, IOptions<DadosBase> dadosBase, IApiToken iApiToken)
        {
            _httpClient = Client.CreateClient();
            _httpClient.DefaultRequestHeaders.Accept.Clear();
            _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            _DadosBase = dadosBase;
            _IApiToken = iApiToken;
        }

        public async Task<ActionResult> Index(string mensagem = null, bool sucesso = true)
        {

            try
            {
                if (sucesso)
                    TempData["sucesso"] = mensagem;
                else
                    TempData["erro"] = mensagem;

                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await _IApiToken.Obter());
                HttpResponseMessage response = await _httpClient.GetAsync($"{_DadosBase.Value.API_URL_BASE}Medico/GetMedicos");

                if (response.IsSuccessStatusCode)
                    return View(JsonConvert.DeserializeObject<List<tUser>>(await response.Content.ReadAsStringAsync()));
                else
                    return View();
            }
            catch (Exception)
            {

                throw;
            }

        }


        public async Task<ActionResult> Create()
        {

            ViewBag.Clinicas = await CarregarClinica();
            tMedicoRetorno tMedicoRetorno = new tMedicoRetorno()
            {
                tUser = new tUser()
                {
                    Ativo = true,
                    DataCriacao = DateTime.Now,
                }

            };
            return View(tMedicoRetorno);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(tMedicoRetorno tMedicoRetorno)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await _IApiToken.Obter());
                    HttpResponseMessage response = await _httpClient.PostAsJsonAsync($"{_DadosBase.Value.API_URL_BASE}Medico/CreateMedico", tMedicoRetorno);

                    if (response.IsSuccessStatusCode)
                        return RedirectToAction(nameof(Index), new { mensagem = "Salvo com sucesso", sucesso = true });
                    else
                        return View(tMedicoRetorno);
                }
                else
                {
                    return View(tMedicoRetorno);
                }
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Edit(int id)
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(int id)
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }









        private async Task<List<SelectListItem>> CarregarClinica()
        {
            List<SelectListItem> lista = new List<SelectListItem>();

            _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await _IApiToken.Obter());

            HttpResponseMessage response = await _httpClient.GetAsync($"{_DadosBase.Value.API_URL_BASE}Medico/GetClinicas");

            if (response.IsSuccessStatusCode)
            {
                string conteudo = await response.Content.ReadAsStringAsync();
                List<SelectClinica> clinica = JsonConvert.DeserializeObject<List<SelectClinica>>(conteudo);

                foreach (var linha in clinica)
                {
                    lista.Add(new SelectListItem()
                    {
                        Value = linha.ID.ToString(),
                        Text = linha.Nome,
                        Selected = false,
                    });
                }

                return lista;
            }
            else
            {
                throw new Exception(response.ReasonPhrase);
            }
        }









    }
}

MaisSaude/Controllers/Area/Operador/TitularController.cs
using MaisSaude.Extensoes;
using MaisSaude.Models;
using MaisSaude.Models.tUser;
using MaisSaude.Models.tUser.tTitular;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System.Net.Http.Headers;

namespace MaisSaude.Controllers.Area.Operador
{
    //[Authorize(Roles = "4")]//clinica
    public class TitularController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IOptions<DadosBase> _DadosBase;
        private readonly IApiToken _IApiToken;

        public TitularController(IHttpClientFactory Client, IHttpContextAccessor cookies, IOptions<DadosBase> dadosBase, IApiToken iApiToken)
        {
            _httpClient = Client.CreateClient();
            _httpClient.DefaultRequestHeaders.Accept.Clear();
            _httpClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            _DadosBase = dadosBase;
            _IApiToken = iApiToken;
        }

        public async Task<ActionResult> Index(string mensagem = null, bool sucesso = true)
        {
            try
            {
                if (sucesso)
                    TempData["sucesso"] = mensagem;
                else
                    TempData["erro"] = mensagem;

                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await _IApiToken.Obter());
                HttpResponseMessage response = await _httpClient.GetAsync($"{_DadosBase.Value.API_URL_BASE}Titular/GetTitulares");

                if (response.IsSuccessStatusCode)
                    return View(JsonConvert.DeserializeObject<List<tUser>>(await response.Content.ReadAsStringAsync()));
                else
                    return View();
            }
            catch (Exception)
            {

                throw;
            }

        }

        #region CREATE
        public ActionResult Create()
        {
            tTitularRetorno tUserRetorno = new tTitularRetorno()
            {
                tUser = new tUser()
                {
                    Ativo = true,
                    DataCriacao = DateTime.Now,
                }

            };

            return View(tUserRetorno);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(tTitularRetorno tTitularRetorno)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await _IApiToken.Obter());
                    HttpResponseMessage response = await _httpClient.PostAsJsonAsync($"{_DadosBase.Value.API_URL_BASE}Titular/CreateTitular", tTitularRetorno);

                    if (response.IsSuccessStatusCode)
                        return RedirectToAction(nameof(Index), new { mensagem = "Salvo com sucesso", sucesso = true });
                    else
                        return View(tTitularRetorno);
                }
                else
                {
                    return View(tTitularRetorno);
                }
            }
            catch
            {
                return View();
            }
        }



        #endregion


        public async Task<ActionResult> Edit(int ID)
        {
            try
            {
                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await _IApiToken.Obter());
                HttpResponseMessage response = await _httpClient.GetAsync($"{_DadosBase.Value.API_URL_BASE}Titular/GetTitular?ID={ID}");

                if (response.IsSuccessStatusCode)
                    return View(JsonConvert.DeserializeObject<tTitularRetorno>(await response.Content.ReadAsStringAsync()));
                else
                    return View();
            }
            catch (Exception)
            {
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(tTitularRetorno tTitularRetorno)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", await _IApiToken.Obter());
                    HttpResponseMessage response = await _httpClient.PutAsJsonAsync($"{_DadosBase.Value.API_URL_BASE}Titular/UpdateTitular", tTitularRetorno);

                    if (response.IsSuccessStatusCode)
                        return RedirectToAction(nameof(Index), new { mensagem = "Editado com sucesso", sucesso = true });
                    else
                        return View(tTitularRetorno);
                }
                else
                {
                    return View(tTitularRetorno);
                }
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Delete(int id)
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

MaisSaude/Views/Shared/_Layout.cshtml
@using System.Security.Claims;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MaisSaude</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MaisSaude.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/toastr.js/toastr.css" asp-append-version="true" />
    <link href="~/lib/datatables.net-bs5/datatables.bootstrap5.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        @if (User.FindFirst(ClaimTypes.Name)?.Value != null)
        {
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 Gradiente">
                <div class="container-fluid">
                    <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">MaisSaude</a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            <li class="nav-item ">
                                <a class="nav-link text-white" asp-area="" asp-controller="Titular" asp-action="Index">Agendamento</a>
                            </li>
                        </ul>


                        @if (User.Claims.Where(c => c.Type == ClaimTypes.Role).Select(c => c.Value).FirstOrDefault() == "2")
                        {

                            <div class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">
                                    <font color="white">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" fill="currentColor" class="bi bi-plus-square-fill" viewBox="0 0 16 16">
                                            <path d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm6.5 4.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3a.5.5 0 0 1 1 0z" />
                                        </svg>  Cadastro
                                    </font>
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Titular" asp-action="Index">
                                            Titular
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Dependente" asp-action="Index">
                                            Dependente
                                        </a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Medico" asp-action="Index">
                                            Médico
                                        </a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link" asp-area="" asp-controller="Clinica" asp-action="Index">
                                            Clinica
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        }
                        <ul class="navbar-nav flex-grow- justify-content-end">
                            <li class="nav-item text-center">

                                <a id="UserName" class="text-white" style="font-size: small; margin-right:10px;text-decoration: none ">@User.FindFirst(ClaimTypes.Name)?.Value</a>

                                <div id="btnSair" class="btn-group">
                                    <button id="Sair" class="btn btn-outline-light btn-sm text-white">Sair</button>
                                    <button class="btn btn-outline-light btn-sm  dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" data-bs-targed="#MenuUser" aria-expanded="false"> </button>

                                    <ul id="MenuUser" class="dropdown-menu dropdown-menu-lg-end">
                                        <a asp-area="" asp-controller="Login" asp-action="UpdateUser" class="dropdown-item btn-sm">Editar dados cadastrais</a>
                                    </ul>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MaisSaude - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/inputmask/jquery.inputmask.bundle.min.js"></script>
    <script src="~/lib/toastr.js/toastr.min.js"></script>
    <script src="~/js/global.js" asp-append-version="true"></script>
    <script src="~/lib/datatables.net/jquery.datatables.min.js"></script>
    <script src="~/lib/datatables.net-bs5/datatables.bootstrap5.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
<script>
    $(function () {
        if (document.getElementById('Sair')) {
            document.getElementById('Sair').addEventListener('click', function () {
                window.location.href = '@Url.Action("Login","Login")';
            })
        }
        if ("@TempData["sucesso"]")
            toastr.success("@TempData["sucesso"]");
        if ("@TempData["erro"]")
            toastr.error("@TempData["erro"]");
        if ("@TempData["warning"]")
            toastr.warning("@TempData["warning"]");
    });
</script>